version: '3.8'
services:
  web:
    build: 
        context: .
        dockerfile: Dockerfile        
    container_name: docker-deploy-artifacts-na-mao-web
    ports:
      - "8080:8080"
    environment:
        - ASPNETCORE_URLS=http://+:8080
        - ASPNETCORE_ENVIRONMENT=Starging
        - ConnectionStrings__DefaultConnection=Server=sqlserver;Initial Catalog=master;Persist Security Info=False;User ID=sa;Password=Admin@123;MultipleActiveResultSets=False;
        - TZ=America/Fortaleza    
    depends_on:
      - sqlserver 
    links:
        - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: docker-deploy-artifacts-na-mao-banco-de-dados
    ports:
      - "1433:1433"
    environment:
        - SA_PASSWORD=Admin@123
        - ACCEPT_EULA=Y        
        - TZ=America/Fortaleza
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "Admin@123", "-Q", "select 1"] 
      timeout: 1s
      retries: 10
    
    