version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest    
    container_name: docker-deploy-artifacts-na-mao-banco-de-dados-sqlserver        
    restart: always      
    environment:
        - SA_PASSWORD=${PASSWORD_SQL_SERVER}
        - ACCEPT_EULA=Y        
        - TZ=America/Fortaleza #https://medium.com/@leandrobianch/dicas-docker-fuso-hor%C3%A1rio-sqlserver-efebe5a342b5
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "${PASSWORD_SQL_SERVER}", "-Q", "select 1"]
      interval: 1s
      retries: 20 
  web:
    image: leandrobianch/etapas-ci-cd-net-core-corporativo-com-docker
    container_name: docker-deploy-artifacts-na-mao-web  
    ports:
      - "80:80"
    restart: always    
    environment:
        - ASPNETCORE_URLS=http://+:80
        - ASPNETCORE_ENVIRONMENT=Production
        - HostNameHealthCheck=http://localhost:80
        - TZ=America/Fortaleza #https://medium.com/@leandrobianch/dicas-docker-fuso-hor%C3%A1rio-sqlserver-efebe5a342b5        
        - ConnectionStrings__DefaultConnection=${ConnectionStrings}
    depends_on:
      - sqlserver
    links:
        - sqlserver